services:
  moneymate:
    image: ghcr.io/bimadewantoro/moneymate-web:latest
    container_name: moneymate-web
    restart: unless-stopped
    ports:
      - "3030:3030"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=3030
      - HOSTNAME=0.0.0.0
      - AUTH_TRUST_HOST=true
